/*globals define*/
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.20.5 from webgme on Sun Jan 02 2022 18:33:37 GMT-0600 (Central Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'webgme-json/jsonFunctions'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase,
    JsonFunctions) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of ExportJSON.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin ExportJSON.
     * @constructor
     */
    function ExportJSON() {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructure etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    ExportJSON.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    ExportJSON.prototype = Object.create(PluginBase.prototype);
    ExportJSON.prototype.constructor = ExportJSON;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(Error|null, plugin.PluginResult)} callback - the result callback
     */
    ExportJSON.prototype.main = function (callback) {
        // Use this to access core, project, result, logger etc from PluginBase.
        const self = this;
        const core = self.core;
        const JsonObjectNode = self.activeNode;
        const META = self.META;
        let nodes = null;
        const config = self.getCurrentConfig();

        
        if(!core.isInstanceOf(JsonObjectNode,META.ObjectElement) && !core.isInstanceOf(JsonObjectNode,META.ArrayElement)) {
            self.logger.error('Only arrays and objects can be exported!!');
            callback(new Error('Only objects and arrays can be exported!!!'), null);
            return;
        }

        core.loadSubTree(JsonObjectNode)
        .then(nodes_ => {
            nodes = {};
            nodes_.forEach(node => {
                nodes[core.getPath(node)] = node;
            });

            const result = JsonFunctions.JSONHierarchyToString(nodes, JsonObjectNode, core, META, self.logger);
            
            return self.blobClient.putFile((config.name || 'export')+'.json', result);
        })
        .then(filehash => {
            self.result.addArtifact(filehash);
            self.result.setSuccess(true);
            callback(null, self.result);
        })
        .catch(err => {
            self.logger.error(err.stack);
            callback(err, null);
        });
    };
    
    return ExportJSON;
});
